# Generated by Django 5.2.7 on 2025-10-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='destination',
            name='destination_name_allowed',
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
