# Generated by Django 5.2.7 on 2025-10-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_destination_destination_name_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(choices=[('Siwa', 'Siwa'), ('Fayoum', 'Fayoum'), ('White & Black Desert', 'White & Black Desert'), ('Farafra', 'Farafra'), ('Dakhla', 'Dakhla'), ('Kharga', 'Kharga')], max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['Siwa', 'Fayoum', 'White & Black Desert', 'Farafra', 'Dakhla', 'Kharga'])), name='destination_name_allowed'),
        ),
    ]
