# Generated by Django 5.2.7 on 2025-10-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_destination_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='card_image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='destination',
            name='cta_label',
            field=models.CharField(default='View Details', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='cta_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='featured_position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
