# Generated by Django 5.2.7 on 2025-10-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_destination_card_image_destination_cta_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='cta_url',
        ),
    ]
