# Generated by Django 5.2.7 on 2025-10-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_destination_cta_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='cta_label',
        ),
    ]
