# Generated by Django 5.2.7 on 2025-10-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_trip_additional_destinations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='destination',
            name='destination_name_allowed',
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(choices=[('Siwa', 'Siwa'), ('Fayoum', 'Fayoum'), ('White & Black Desert', 'White & Black Desert'), ('Farafra', 'Farafra'), ('Dakhla', 'Dakhla'), ('Kharga', 'Kharga'), ('Bahareya Oasis', 'Bahareya Oasis')], max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['Siwa', 'Fayoum', 'White & Black Desert', 'Farafra', 'Dakhla', 'Kharga', 'Bahareya Oasis'])), name='destination_name_allowed'),
        ),
    ]
