# Generated by Django 5.2.7 on 2025-10-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_destination_hero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='web.destination')),
            ],
            options={
                'verbose_name': 'Destination gallery image',
                'verbose_name_plural': 'Destination gallery images',
                'ordering': ['position', 'id'],
            },
        ),
    ]
