# Generated by Django 5.2.7 on 2025-10-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_destinationgalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Discover the Magic of Egypt', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Embark on an unforgettable journey through ancient wonders and timeless beauty')),
                ('hero_primary_cta_label', models.CharField(default='Explore Tours', max_length=100)),
                ('hero_primary_cta_href', models.CharField(default='/trips', max_length=255)),
                ('hero_secondary_cta_label', models.CharField(default='Learn More', max_length=100)),
                ('hero_secondary_cta_href', models.CharField(default='#about', max_length=255)),
                ('hero_image', models.ImageField(blank=True, upload_to='site/hero/')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
