# Generated by Django 5.2.7 on 2025-10-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_blogcategory_blogpost_blogsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='trips_hero_image',
            field=models.ImageField(blank=True, upload_to='site/trips_hero/'),
        ),
    ]
