# Generated by Django 5.2.7 on 2025-10-20 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_siteconfiguration_trips_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Video shown on desktop hero. Prefer optimized MP4/WebM under 10 MB.', upload_to='site/hero/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])]),
        ),
    ]
