# Generated by Django 5.2.7 on 2025-10-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_siteconfiguration_hero_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(blank=True, default='Discover the Magic of Egypt', max_length=200),
        ),
    ]
