# Generated by Django 5.2.7 on 2025-10-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_siteconfiguration_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='gallery_background_image',
            field=models.ImageField(blank=True, help_text='Optional background image for the gallery marquee frame.', upload_to='site/gallery/frame/'),
        ),
    ]
