# Generated by Django 5.2.7 on 2025-10-22 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_siteconfiguration_gallery_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='status_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
