# Generated by Django 5.2.7 on 2025-10-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_booking_status_booking_status_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group_reference',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
