# Generated by Django 5.2.7 on 2025-10-24 15:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_booking_group_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHeroPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Optional internal name to help identify this pair.', max_length=150)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first on the homepage hero.')),
                ('hero_image', models.ImageField(blank=True, help_text='Desktop/mobile hero image, or poster fallback when a video is provided.', upload_to='site/hero/pairs/')),
                ('hero_video', models.FileField(blank=True, help_text='Optional background video. Keep under 10 MB for best performance.', upload_to='site/hero/pairs/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])])),
                ('overlay_image', models.ImageField(blank=True, help_text='Smaller layered image displayed on top of the hero banner.', upload_to='site/hero/pairs/overlay/')),
                ('overlay_alt', models.CharField(blank=True, help_text='Describe the overlay image for accessibility (leave empty if decorative).', max_length=200)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_pairs', to='web.siteconfiguration')),
            ],
            options={
                'verbose_name': 'Hero pair',
                'verbose_name_plural': 'Hero pairs',
                'ordering': ['position', 'id'],
            },
        ),
    ]
