# Generated by Django 5.2.7 on 2025-10-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_remove_destination_destination_name_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='destination',
            name='destination_name_allowed',
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(choices=[('Siwa', 'Siwa'), ('Fayoum', 'Fayoum'), ('White & Black Desert', 'White & Black Desert'), ('Farafra', 'Farafra'), ('Dakhla', 'Dakhla'), ('Kharga', 'Kharga'), ('Bahareya Oasis', 'Bahareya Oasis'), ('Giza', 'Giza'), ('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Ain El Sokhna', 'Ain El Sokhna'), ('Sinai', 'Sinai'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan')], max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['Siwa', 'Fayoum', 'White & Black Desert', 'Farafra', 'Dakhla', 'Kharga', 'Bahareya Oasis', 'Giza', 'Cairo', 'Alexandria', 'Ain El Sokhna', 'Sinai', 'Luxor', 'Aswan'])), name='destination_name_allowed'),
        ),
    ]
