# Generated by Django 5.1.5 on 2025-10-28 01:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_remove_destination_destination_name_allowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=15)),
                ('threshold_amount', models.DecimalField(decimal_places=2, help_text='Subtotal required to unlock this reward tier.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Percentage discount applied to eligible trips.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('headline', models.CharField(blank=True, help_text='Optional short pitch shown on checkout rewards panel.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer copy explaining the reward benefits.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RewardPhaseTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Controls the display order for eligible trips within the phase.')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_trips', to='web.rewardphase')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reward_phases', to='web.trip')),
            ],
            options={
                'ordering': ['phase', 'position', 'id'],
                'unique_together': {('phase', 'trip')},
            },
        ),
        migrations.AddField(
            model_name='rewardphase',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='reward_phases', through='web.RewardPhaseTrip', to='web.trip'),
        ),
        migrations.CreateModel(
            name='BookingReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler_count', models.PositiveIntegerField()),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='web.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_rewards', to='web.trip')),
                ('reward_phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_rewards', to='web.rewardphase')),
            ],
            options={
                'ordering': ['-applied_at'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'reward_phase', 'trip'), name='unique_reward_phase_per_booking_trip')],
            },
        ),
        migrations.AddIndex(
            model_name='rewardphase',
            index=models.Index(fields=['status'], name='web_rewardp_status_41392b_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardphase',
            index=models.Index(fields=['position'], name='web_rewardp_positio_f900c2_idx'),
        ),
    ]
