# Generated by Django 5.2.7 on 2025-10-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_rewardphase_rewardphasetrip_rewardphase_trips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_service',
            field=models.BooleanField(default=False, help_text='Mark this trip as a service-only add-on for quick checkout adds.'),
        ),
    ]
