# Generated by Django 5.2.7 on 2025-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_trip_is_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional heading shown in the homepage gallery.', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Short description displayed on the gallery cards.', max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Describe the image for accessibility (leave empty if decorative).', max_length=200)),
                ('image', models.ImageField(upload_to='site/gallery/')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first on the homepage gallery.')),
                ('is_active', models.BooleanField(default=True, help_text='Disable to temporarily hide the image from the gallery.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing gallery image',
                'verbose_name_plural': 'Landing gallery images',
                'ordering': ['position', 'id'],
            },
        ),
    ]
