# Generated by Django 5.2.7 on 2025-10-29 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_landinggalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trips/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='web.trip')),
            ],
            options={
                'verbose_name': 'Trip gallery image',
                'verbose_name_plural': 'Trip gallery images',
                'ordering': ['position', 'id'],
            },
        ),
    ]
