# Generated by Django 5.2.7 on 2025-10-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_tripgalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingConfirmationEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Automatically send a confirmation email whenever a booking is marked as confirmed.')),
                ('from_email', models.EmailField(blank=True, help_text='Sender address. Leave blank to fall back to DEFAULT_FROM_EMAIL.', max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Optional reply-to address customers will use when responding.', max_length=254)),
                ('cc_addresses', models.TextField(blank=True, help_text='Optional comma-separated list of addresses to CC on each confirmation email.')),
                ('bcc_addresses', models.TextField(blank=True, help_text='Optional comma-separated list of addresses to BCC on each confirmation email.')),
                ('subject_template', models.CharField(default='Your Kaya booking {{ booking.reference_code }} is confirmed', help_text='Django template for the email subject (e.g. {{ booking.reference_code }}).', max_length=200)),
                ('body_text_template', models.TextField(default='Hi {{ booking.full_name }},\n\nWe\'re excited to confirm your trip "{{ trip.title }}" scheduled for {{ booking.travel_date|date:"F j, Y" }}.\n\nBooking summary:\n- Reference: {{ booking.reference_code }}\n- Travelers: {{ booking.adults }} adult{{ booking.adults|pluralize }}{% if booking.children %}, {{ booking.children }} child{{ booking.children|pluralize:"ren" }}{% endif %}{% if booking.infants %}, {{ booking.infants }} infant{{ booking.infants|pluralize }}{% endif %}\n- Total: {{ booking.grand_total|floatformat:2 }}\n\n{% if extras %}\nExtras you\'ve selected:\n{% for item in extras %}\n- {{ item.extra.name }} - {{ item.price_at_booking|floatformat:2 }}\n{% endfor %}\n{% endif %}\n{% if booking.special_requests %}\nSpecial requests:\n{{ booking.special_requests }}\n{% endif %}\n\nOne of our travel specialists will reach out soon with the next steps. If you need any help in the meantime, just reply to this email.\n\nThanks for choosing Kaya Tours!\n', help_text='Plain-text body rendered with Django template syntax.')),
                ('body_html_template', models.TextField(blank=True, help_text='Optional HTML body. Leave blank to auto-convert the text body.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking confirmation email settings',
                'verbose_name_plural': 'Booking confirmation email settings',
            },
        ),
    ]
