# Generated by Django 5.2.7 on 2025-10-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_bookingconfirmationemailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='child_price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-child rate (ages 3–11). Leave blank to match the adult price.', max_digits=10, null=True),
        ),
    ]
