# Generated by Django 5.2.7 on 2025-11-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_trip_child_price_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationgalleryimage',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationgalleryimage',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripgalleryimage',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripgalleryimage',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinationgalleryimage',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='destinations/gallery/', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='tripgalleryimage',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='trips/gallery/', width_field='image_width'),
        ),
    ]
