# Generated by Django 5.2.7 on 2025-11-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_destinationgalleryimage_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='card_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='blog/cards/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='blog/hero/'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='section_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='blog/sections/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='card_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='destinations/hero/'),
        ),
        migrations.AlterField(
            model_name='destinationgalleryimage',
            name='image',
            field=models.ImageField(height_field='image_height', max_length=255, upload_to='destinations/gallery/', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='landinggalleryimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='site/gallery/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='gallery_background_image',
            field=models.ImageField(blank=True, help_text='Optional background image for the gallery marquee frame.', max_length=255, upload_to='site/gallery/frame/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='site/hero/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='trips_hero_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='site/trips_hero/'),
        ),
        migrations.AlterField(
            model_name='siteheropair',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Desktop/mobile hero image, or poster fallback when a video is provided.', max_length=255, upload_to='site/hero/pairs/'),
        ),
        migrations.AlterField(
            model_name='siteheropair',
            name='overlay_image',
            field=models.ImageField(blank=True, help_text='Smaller layered image displayed on top of the hero banner.', max_length=255, upload_to='site/hero/pairs/overlay/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='card_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='trips/cards/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='trips/hero/'),
        ),
        migrations.AlterField(
            model_name='tripgalleryimage',
            name='image',
            field=models.ImageField(height_field='image_height', max_length=255, upload_to='trips/gallery/', width_field='image_width'),
        ),
    ]
