# Generated by Django 5.2.7 on 2025-11-02 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_alter_blogpost_card_image_alter_blogpost_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='hero_image_mobile',
            field=models.ImageField(blank=True, help_text='Optional image optimized for mobile destination hero.', max_length=255, upload_to='destinations/hero/mobile/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_mobile_image',
            field=models.ImageField(blank=True, help_text='Fallback image shown on mobile when no hero pairs exist.', max_length=255, upload_to='site/hero/mobile/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_mobile_video',
            field=models.FileField(blank=True, help_text='Mobile-friendly hero video used when no hero pairs exist.', upload_to='site/hero/videos/mobile/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])]),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='trips_hero_image_mobile',
            field=models.ImageField(blank=True, help_text='Optional hero image displayed on mobile for the trips page.', max_length=255, upload_to='site/trips_hero/mobile/'),
        ),
        migrations.AddField(
            model_name='siteheropair',
            name='hero_mobile_image',
            field=models.ImageField(blank=True, help_text='Mobile-specific hero image override.', max_length=255, upload_to='site/hero/pairs/mobile/'),
        ),
        migrations.AddField(
            model_name='siteheropair',
            name='hero_mobile_video',
            field=models.FileField(blank=True, help_text='Mobile-specific background video override.', upload_to='site/hero/pairs/videos/mobile/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])]),
        ),
        migrations.AddField(
            model_name='trip',
            name='hero_image_mobile',
            field=models.ImageField(blank=True, help_text='Optional hero image tailored for mobile devices.', max_length=255, upload_to='trips/hero/mobile/'),
        ),
    ]
