# Generated by Django 5.2.7 on 2025-11-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_destination_hero_image_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Optional manual ordering for destination-specific listings. Lower numbers appear first.', null=True),
        ),
    ]
