# Generated by Django 5.2.7 on 2025-11-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_trip_destination_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
