# Generated by Django 5.2.7 on 2025-11-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_package_trip_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='allow_children',
            field=models.BooleanField(default=True, help_text='Allow child travelers to be booked for this trip.'),
        ),
        migrations.AddField(
            model_name='trip',
            name='allow_infants',
            field=models.BooleanField(default=True, help_text='Allow infant travelers to be booked for this trip.'),
        ),
        migrations.AddField(
            model_name='trip',
            name='minimum_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum age required for participants (leave blank if none).', null=True),
        ),
    ]
