# Generated by Django 5.2.7 on 2025-11-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_trip_allow_children_trip_allow_infants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip_option_label',
            field=models.CharField(blank=True, help_text='Snapshot of the option name chosen by the guest.', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_option_price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-person rate for the selected option when the booking was created.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingconfirmationemailsettings',
            name='body_text_template',
            field=models.TextField(default='Hi {{ booking.full_name }},\n\nWe\'re excited to confirm your trip "{{ trip.title }}" scheduled for {{ booking.travel_date|date:"F j, Y" }}.\n\nBooking summary:\n- Reference: {{ booking.reference_code }}\n- Travelers: {{ booking.adults }} adult{{ booking.adults|pluralize }}{% if booking.children %}, {{ booking.children }} child{{ booking.children|pluralize:"ren" }}{% endif %}{% if booking.infants %}, {{ booking.infants }} infant{{ booking.infants|pluralize }}{% endif %}\n{% if booking.trip_option_label %}\n- Experience: {{ booking.trip_option_label }}\n{% endif %}\n- Total: {{ booking.grand_total|floatformat:2 }}\n- Total: {{ booking.grand_total|floatformat:2 }}\n\n{% if extras %}\nExtras you\'ve selected:\n{% for item in extras %}\n- {{ item.extra.name }} - {{ item.price_at_booking|floatformat:2 }}\n{% endfor %}\n{% endif %}\n{% if booking.special_requests %}\nSpecial requests:\n{{ booking.special_requests }}\n{% endif %}\n\nOne of our travel specialists will reach out soon with the next steps. If you need any help in the meantime, just reply to this email.\n\nThanks for choosing Sand & Sky Tours!\n', help_text='Plain-text body rendered with Django template syntax.'),
        ),
        migrations.CreateModel(
            name='TripBookingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price_per_person', models.DecimalField(blank=True, decimal_places=2, help_text="Override child rate just for this option. Leave blank to match the trip's child price.", max_digits=10, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_options', to='web.trip')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_option',
            field=models.ForeignKey(blank=True, help_text='Selected booking option, if any, at the time of booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='web.tripbookingoption'),
        ),
    ]
