# Generated by Django 5.2.7 on 2025-11-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_booking_trip_option_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='classification',
            field=models.CharField(choices=[('general', 'General'), ('sahari', 'Sahari')], db_index=True, default='general', max_length=20),
        ),
    ]
