# Generated by Django 5.2.7 on 2025-11-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_destination_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingconfirmationemailsettings',
            name='body_text_template',
            field=models.TextField(default='Hi {{ booking.full_name }},\n\nWe\'re excited to confirm your trip "{{ trip.title }}" scheduled for {{ booking.travel_date|date:"F j, Y" }}.\n\nBooking summary:\n- Reference: {{ booking.reference_code }}\n- Travelers: {{ booking.adults }} adult{{ booking.adults|pluralize }}{% if booking.children %}, {{ booking.children }} child{{ booking.children|pluralize:"ren" }}{% endif %}{% if booking.infants %}, {{ booking.infants }} infant{{ booking.infants|pluralize }}{% endif %}\n{% if booking.trip_option_label %}\n- Experience: {{ booking.trip_option_label }}\n{% endif %}\n- Total: {{ booking.grand_total|floatformat:2 }}\n\n{% if extras %}\nExtras you\'ve selected:\n{% for item in extras %}\n- {{ item.extra.name }} - {{ item.price_at_booking|floatformat:2 }}\n{% endfor %}\n{% endif %}\n{% if booking.special_requests %}\nSpecial requests:\n{{ booking.special_requests }}\n{% endif %}\n\nOne of our travel specialists will reach out soon with the next steps. If you need any help in the meantime, just reply to this email.\n\nThanks for choosing Kaya Tours!\n', help_text='Plain-text body rendered with Django template syntax.'),
        ),
    ]
