# Generated by Django 5.2.7 on 2026-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_alter_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
