"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load simple key=value pairs from BASE_DIR/.env without overriding active env
_env_file = BASE_DIR / ".env"
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if not _line or _line.startswith("#") or "=" not in _line:
            continue
        _key, _value = _line.split("=", 1)
        os.environ.setdefault(_key.strip(), _value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --- Secrets & toggles (env-optional, safe defaults for PA) ---
# SECRET_KEY: env first, else load/create a file-based key at BASE_DIR/.secret_key
_secret_from_env = os.environ.get("DJANGO_SECRET_KEY") or os.environ.get("SECRET_KEY")
if _secret_from_env:
    SECRET_KEY = _secret_from_env
else:
    SECRET_FILE = BASE_DIR / ".secret_key"
    try:
        if SECRET_FILE.exists():
            SECRET_KEY = SECRET_FILE.read_text().strip()
            if not SECRET_KEY:
                raise ValueError("empty secret")
        else:
            raise FileNotFoundError
    except Exception:
        import secrets
        SECRET_KEY = secrets.token_urlsafe(64)
        try:
            SECRET_FILE.write_text(SECRET_KEY)
        except Exception:
            # If we can't write the file (read-only FS), just keep the in-memory key
            pass

# DEBUG: default to False (production) unless explicitly enabled
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in ("1","true","yes","on")

# ALLOWED_HOSTS: use env if non-empty, else safe defaults
_raw_hosts = (os.environ.get("DJANGO_ALLOWED_HOSTS") or "").strip()
if _raw_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = ["adhamidris.pythonanywhere.com", "localhost", "127.0.0.1"]

# CSRF_TRUSTED_ORIGINS: use env if non-empty, else safe defaults
_raw_csrf = (os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS") or "").strip()
if _raw_csrf:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf.split(",") if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = ["https://adhamidris.pythonanywhere.com"]
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS","3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nested_admin',
    'storages',
    'seo.apps.SeoConfig',
    'web.apps.WebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'seo.middleware.SeoRedirectMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.booking_cart',
            ],
            'libraries': {
                'admin_metrics': 'web.templatetags.admin_metrics',
            },
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASS"),
        "HOST": os.getenv("DB_HOST"), 
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'            # collectstatic output

STORAGES = locals().get("STORAGES", {})
STORAGES["staticfiles"] = {
    "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
}

# Media storage defaults (local filesystem)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Cloudflare R2 media storage (S3-compatible) ---
_r2_access_key = os.environ.get("CLOUDFLARE_R2_ACCESS_KEY_ID")
_r2_secret_key = os.environ.get("CLOUDFLARE_R2_SECRET_ACCESS_KEY")
_r2_bucket = os.environ.get("CLOUDFLARE_R2_BUCKET", "sandnsky")
_r2_endpoint = os.environ.get("CLOUDFLARE_R2_ENDPOINT_URL")
if not _r2_endpoint:
    _r2_account = os.environ.get("CLOUDFLARE_R2_ACCOUNT_ID")
    if _r2_account:
        _r2_endpoint = f"https://{_r2_account}.r2.cloudflarestorage.com"

_use_r2_media = all([_r2_access_key, _r2_secret_key, _r2_bucket, _r2_endpoint])

if _use_r2_media:
    AWS_ACCESS_KEY_ID = _r2_access_key
    AWS_SECRET_ACCESS_KEY = _r2_secret_key
    AWS_STORAGE_BUCKET_NAME = _r2_bucket
    AWS_S3_ENDPOINT_URL = _r2_endpoint.rstrip("/")
    AWS_S3_REGION_NAME = os.environ.get("CLOUDFLARE_R2_REGION", "auto")
    AWS_S3_SIGNATURE_VERSION = os.environ.get("CLOUDFLARE_R2_SIGNATURE_VERSION", "s3v4")
    AWS_S3_ADDRESSING_STYLE = os.environ.get("CLOUDFLARE_R2_ADDRESSING_STYLE", "path")
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = os.environ.get("CLOUDFLARE_R2_SIGNED_URLS", "False").lower() in ("1", "true", "yes", "on")
    _cache_control = os.environ.get("CLOUDFLARE_R2_CACHE_CONTROL", "max-age=86400")
    if _cache_control:
        AWS_S3_OBJECT_PARAMETERS = {"CacheControl": _cache_control}
    AWS_S3_FILE_OVERWRITE = False

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

    _r2_public_domain = os.environ.get("CLOUDFLARE_R2_PUBLIC_DOMAIN")
    if _r2_public_domain:
        _r2_public_domain = _r2_public_domain.strip().rstrip("/")
        if _r2_public_domain.startswith("http://") or _r2_public_domain.startswith("https://"):
            _r2_public_domain = _r2_public_domain.split("://", 1)[1]
        AWS_S3_CUSTOM_DOMAIN = _r2_public_domain
        MEDIA_URL = f"https://{_r2_public_domain}/"
    else:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{_r2_bucket}/"

    MEDIA_ROOT = None

# Email delivery -------------------------------------------------------------

EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
    if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend",
)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL",
    "Kaya Tours <no-reply@example.com>",
)

EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS", "True").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
EMAIL_USE_SSL = os.environ.get("DJANGO_EMAIL_USE_SSL", "False").lower() in (
    "1",
    "true",
    "yes",
    "on",
)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
