# Generated by Django 5.2.7 on 2025-11-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_backfill_seo_entries'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seoentry',
            new_name='seo_seoentr_page_ty_9ceb47_idx',
            old_name='seo_seoentr_page_ty_b61dd1_idx',
        ),
        migrations.RenameIndex(
            model_name='seoentry',
            new_name='seo_seoentr_page_ty_3412f3_idx',
            old_name='seo_seoentr_page_ty_1d98f4_idx',
        ),
    ]
